name: Build StardewSkills (BetterHud + PAPI)

on:
  workflow_dispatch: {}   # 수동 실행 버튼
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew || true
      - name: Build with Gradle (download wrapper if missing)
        run: |
          if [ ! -f gradlew ]; then
            echo "Gradle wrapper missing. Generating..."
            printf "plugins { id 'java' }\n" > temp.gradle
            ./gradlew wrapper || (curl -s https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o gradlew && chmod +x gradlew && echo "fallback wrapper fetched")
          fi
          ./gradlew --no-daemon build
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: stardewskills-jar
          path: build/libs/*.jar
