name: Build StardewSkills (BetterHud + PAPI)

on:
  workflow_dispatch: {}
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Detect project dir
        id: detect
        shell: bash
        run: |
          echo "Workspace:"
          ls -la
          if [ -f build.gradle ]; then
            echo "proj=." >> $GITHUB_OUTPUT
          elif [ -f StardewSkills-BetterHud-PAPI/build.gradle ]; then
            echo "proj=StardewSkills-BetterHud-PAPI" >> $GITHUB_OUTPUT
          else
            # 가장 흔한 2중 폴더 케이스를 폭넓게 탐색
            CAND=$(find . -maxdepth 2 -type f -name build.gradle | head -n1)
            if [ -n "$CAND" ]; then
              DIR=$(dirname "$CAND")
              echo "proj=${DIR#.}" >> $GITHUB_OUTPUT
            else
              echo "build.gradle not found"; exit 1
            fi
          fi
          echo "Using project dir: ${{ steps.detect.outputs.proj }}"

      - name: Build with Gradle
        shell: bash
        run: |
          cd "${{ steps.detect.outputs.proj }}"
          gradle build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: stardewskills-jar
          path: |
            build/libs/*.jar
            ${{ steps.detect.outputs.proj }}/build/libs/*.jar
          if-no-files-found: warn
